- name: Starting Cassandra service
  service: name=cassandra enabled=yes state=restarted
  when: " {{ cassandra_node_filter }} "

- name: Verify Cassandra is running
  shell: "nodetool status | grep `curl http://169.254.169.254/latest/meta-data/public-ipv4`"
  register: result
  until: result|success and result.stdout.split()[0] == 'UN'
  retries: 10
  delay: 15
  when: " {{ cassandra_node_filter }} "
  changed_when: false
