dependencies:
  - gcc-c++
  - patch
  - readline
  - readline-devel
  - zlib
  - zlib-devel
  - libyaml-devel
  - libffi-devel
  - openssl-devel
  - make
  - bzip2
  - autoconf
  - automake
  - libtool
  - bison
#  - iconv-devel
