cassandra_cqlsh_port : 9042
keyspace_query : "CREATE KEYSPACE IF NOT EXISTS cqlmigrate WITH replication = {'class': 'NetworkTopologyStrategy', {{ data_centre_to_replication_factor_strings | join(', ') }} }"
table_query : "CREATE TABLE IF NOT EXISTS cqlmigrate.locks (name text PRIMARY KEY, client text)"
data_centre_to_replication_factor_strings:
  - "'datacenter1': 3"
